---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luxuming.
--- DateTime: 2021/9/11 16:18
---

local RedTipUtility = {}

function RedTipUtility:findRedTipBaseByStrKey(strKey, redTipBase)
    if redTipBase == nil then
        return false, nil
    end
    if redTipBase:isEqualByStrKey(strKey) then
        return true, redTipBase
    end

    if not redTipBase:hasChildNode() then
        return false, nil
    end

    local redRedTipBase

    local iter = redTipBase:getChildrenIterator()
    local childNode = nil
    repeat
        childNode = iter:next()
        local findFlag, findRedTipBase = self:findRedTipBaseByStrKey(strKey, childNode)
        if findFlag then
            redRedTipBase = findRedTipBase
            break
        end
    until (childNode == nil)
    return redRedTipBase ~= nil, redRedTipBase
end

return RedTipUtility